# Generated by Django 4.1 on 2023-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/models')),
            ],
        ),
    ]
