# Generated by Django 4.1 on 2023-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
