# Generated by Django 4.1 on 2023-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlmodel',
            name='document',
            field=models.ImageField(upload_to='uploads/models'),
        ),
    ]
