# Generated by Django 4.1 on 2023-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='uploads/images')),
            ],
        ),
    ]
