# Generated by Django 4.1 on 2023-07-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_imagedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='uploads/images')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
